services:
  db:
    image: mysql:8
    container_name: gestao_condominio_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestao_condominios
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  api:
    image: gestao-condominio-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao_condominio_api
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "./wait-for.sh app_db:3306 sh -c 'npx prisma migrate deploy && node dist/server.js'"

volumes:
  mysql_data:
